var rimMessage = {
		 LoadingProcessing : "데이터 처리중입니다.잠시만기다려 주세요...",
		 GroupStorage : "그룹 저장소",
		 PersonalStorage : "개인 저장소",
		 Tags : "태그",
		 Version : "버전",
		 Property : "속성",
		 ValidateName : " 은(는) <BR> 특수문자등이 포함되어 사용할수없습니다.",
		 ConfirmChangeUseN : "을(를) 미운영상태로 변경하시겠습니까?",
		 ConfirmChangeUseY : " 을(를) 운영상태로 변경하시겠습니까?",
		 ConfirmDelete : "삭제하시겠습니까?",
		 ConfirmDeleteFile : "삭제된 폴더 및 파일은 휴지통으로 이동합니다.<BR>삭제하시겠습니까?",
		 ConfirmDeleteVersion : "버전 파일 삭제시 복구할수없습니다.<BR>삭제하시겠습니까?",
		 ConfirmDownloadApprove : " 문서에 대해 다운로드 승인 하시겠습니까?",
		 ConfirmDownloadUnapprove : " 문서에 대해 다운로드 미승인 하시겠습니까?",
		 Paste : "붙여넣기",
		 Delete : "삭제",
		 DeleteAll : "전체삭제",
		 EmptyVersionList : "버전파일이 존재하지 않습니다.",
		 Download : "다운로드",
		 DownloadFailed : "다운로드중 오류가 발생했습니다.",
		 ReStore : "복원",
		 ReStorePath : "복원위치",
		 FileName : "파일이름",
		 FileSize : "파일크기",
		 FilePath : "파일위치",
		 ModifyDateTime : "수정날짜",
		 CreateDateTime : "생성날짜",
		 NotifyFolderInfo : "폴더 {0}개 그리고 파일 {1}개  {2} (총 {3}개)",
		 NotifyPaging : "총 {0}페이지중 {1}페이지",
		 ConfirmRestore : "복원 하시겠습니까?",
		 ConfirmDeleteTrashBin : "휴지통 파일 삭제시 복구할수없습니다.<BR>삭제하시겠습니까?",
		 DuplicatePaste : "같은 폴더에 붙여넣기 할수없습니다.",
		 AlertTitle : "알림",
		 Ok : "확인",
		 Cancel : "취소",
		 ConfirmTitle : "확인",
		 FailSessionTimeout : "세선이 종료되었습니다.",
		 SeleteUser : "사용자를 선택하여 주세요.",
		 SeleteDept : "부서를 선택하여 주세요.",
		 SelectUpperDept : "상위 부서를 선택하여 주세요.",
		 SeleteAdmin : "관리자를 선택하여 주세요.",
		 SelectOptYn : "운영 여부를 선택하여 주세요.",
		 ConfirmDeleteUser : " 사용자 계정 정보를 삭제 하시겠습니까?",
		 ConfirmDeleteDept : " 부서 정보를 삭제 하시겠습니까?",
		 ConfirmDeleteGroupStorage : " 그룹저장소  삭제시 복구할수 없습니다. 삭제 하시겠습니까?",
		 ConfirmExpireDate : "일까지 다운로드가능",
		 InputGroupName : "그룹저장소 이름을 입력하여 주세요.",
		 InputQuota : "할당용량을 입력하여 주세요.",
		 InputDeptCode : "부서코드를 입력하여 주세요.",
		 InputDeptName : "부서명을 입력하여 주세요.",
		 InputSortSord : "정렬순서를 숫자로 입력하여 주세요.",
		 InputLoginId : "사용자 ID를 입력하여 주세요.",
		 InputUserName : "사용자명을 입력하여 주세요.",
		 InputUserGrade : "직급을 입력하여 주세요.",
		 InputSamePassword : "비밀번호를 동일하게 입력하여 주세요.",
		 EmptyUserList : "사용자가 존재하지 않습니다.",
		 AlertInputFileName : "파일(폴더) 이름을 입력하여 주세요.",
		 AlertNotChangeSameOwner : "동일 사용자는 소유권 이전 할 수 없습니다.",
		 AlertNotExistUser : "해당하는 사용자가 존재하지 않습니다.",
		 DetailViewOpen : "자세히 열기",
		 DetailViewClose : "자세히 닫기",
		 Uploading : "업로드 중",
		 UploadDone : "업로드 완료",
		 UploadCancelAll : "전체취소",
		 UploadDoneClear : "완료목록 지우기",
		 UploadSize : "전송크기",
		 UploadProcess : "진행상태",
		 TotalCount : "전체건수",
		 RefreshMsg : "정보가 저장되지 않을 수도 있습니다. 새로고침 하시겠습니까?",
		 FailMsg : "요청이 처리되지 않았습니다.<BR>잠시 후 다시 시도하여 주세요.",
		 NoAuthMsg : "접근 권한이 없습니다.<BR>확인 후 다시 시도하여 주세요.",
		 FolderSize : "폴더크기",
		 FolderCount : "폴더수",
		 FileCount : "파일수",
		 ExpiredDateMsg : "유효기간 설정정보가 없습니다.",
};

